INSERT INTO MISSION (CONTENT) values ('[하] 패트병 라벨 뜯어서 버리기');
INSERT INTO MISSION (CONTENT) values ('[하] 음식물 남기지 않기');
INSERT INTO MISSION (CONTENT) values ('[하] 대중교통 이용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 텀블러 사용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 장바구니 사용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 손수건 사용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 안쓰는 전기코드 뽑기');
INSERT INTO MISSION (CONTENT) values ('[하] 길가에 보이는 쓰레기 줍기');
INSERT INTO MISSION (CONTENT) values ('[하] 플라스틱 세척해서 버리기');
INSERT INTO MISSION (CONTENT) values ('[하] 양치컵 사용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 물 받아서 세수하기');
INSERT INTO MISSION (CONTENT) values ('[하] 비누칠할 때 물 잠그기');
INSERT INTO MISSION (CONTENT) values ('[하] 종량제 봉투 사용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 환경 관련 기사 살펴보기');
INSERT INTO MISSION (CONTENT) values ('[하] 물티슈 대신 행주 사용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 종이컵 사용하지 않기');
INSERT INTO MISSION (CONTENT) values ('[하] 분리수거 하기');
INSERT INTO MISSION (CONTENT) values ('[하] 음료수 캔 세척해서 버리기');
INSERT INTO MISSION (CONTENT) values ('[하] 플라스틱 부피 줄여서 버리기');
INSERT INTO MISSION (CONTENT) values ('[하] 비건 레시피 찾아보기');
INSERT INTO MISSION (CONTENT) values ('[하] 이산화 탄소 농도 찾아보기');
INSERT INTO MISSION (CONTENT) values ('[하] 메일함 비우기');
INSERT INTO MISSION (CONTENT) values ('[하] 쇼핑백 받지 않기');
INSERT INTO MISSION (CONTENT) values ('[하] 낮 시간 형광등 대신 커튼 걷기');
INSERT INTO MISSION (CONTENT) values ('[하] 요리할 때 뚜껑 이용하기');
INSERT INTO MISSION (CONTENT) values ('[하] 쿨 맵시 & 온 맵시 실천하기');
INSERT INTO MISSION (CONTENT) values ('[하] 커뮤니티에 캠페인 제안하기');
INSERT INTO MISSION (CONTENT) values ('[하] 커뮤니티 캠페인 참여하기');
INSERT INTO MISSION (CONTENT) values ('[하] 캠페인 인증글 게시하기');
INSERT INTO MISSION (CONTENT) values ('[하] 다른 사람의 인증글 좋아요 누르기');
INSERT INTO MISSION (CONTENT) values ('[중] 탄소 발자국 계산기 사용해보기');
INSERT INTO MISSION (CONTENT) values ('[중] 종이 대신 모바일 영수증 사용하기');
INSERT INTO MISSION (CONTENT) values ('[중] 쌀뜨물 재사용 해보기');
INSERT INTO MISSION (CONTENT) values ('[중] 한끼 식사 채식하기');
INSERT INTO MISSION (CONTENT) values ('[중] 종이빨대 사용하기');
INSERT INTO MISSION (CONTENT) values ('[중] 재사용 병 사용해보기');
INSERT INTO MISSION (CONTENT) values ('[중] 다회 용기 사용해서 음식 포장하기');
INSERT INTO MISSION (CONTENT) values ('[중] 식당에서 일회용품 사용하지 않기');
INSERT INTO MISSION (CONTENT) values ('[중] 엘레베이터 대신 계단 이용하기');
INSERT INTO MISSION (CONTENT) values ('[중] 환경 관련 다큐멘터리 찾아보기');
INSERT INTO MISSION (CONTENT) values ('[중] 환경 단체 알아보기');
INSERT INTO MISSION (CONTENT) values ('[중] 한시간 더 일찍 자기');
INSERT INTO MISSION (CONTENT) values ('[중] 오늘 하루 아무 것도 사지 않기');
INSERT INTO MISSION (CONTENT) values ('[중] 먹지 않는 약 약국에 반납하기');
INSERT INTO MISSION (CONTENT) values ('[상] 리사이클 매장 방문해보기');
INSERT INTO MISSION (CONTENT) values ('[상] 폐건전지 전용 수거함에 버리기');
INSERT INTO MISSION (CONTENT) values ('[상] 중고거래 이용해보기');
INSERT INTO MISSION (CONTENT) values ('[상] 폐식용유 처리함 이용해보기');
INSERT INTO MISSION (CONTENT) values ('[상] 밀가루로 빨래해보기');
INSERT INTO MISSION (CONTENT) values ('[상] 식물 심기');
INSERT INTO MISSION (CONTENT) values ('[상] 망가진 물건 고쳐 쓰기');